package com.qurishimi.touch.encje;
// Generated 2017-10-10 09:59:00 by Hibernate Tools 5.2.5.Final

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer id;
	private User user;
	private String model;

	public Car() {
	}

	public Car(User user, String model) {
		this.user = user;
		this.model = model;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

}
